
dataset:
  video_fp: /some/file/that/does/not/care.mp4  # do not change
  gcp:
    apply: true  # do not change
    pixels:
    - - 552
      - 403
    - - 2551
      - 2121
    - - 3575
      - 1041
    - - 830
      - 242
    distances:
      "(0,1)": 19.0869
      "(0,2)": 21.8399
      "(0,3)": 3.7782
      "(1,2)": 8.3321
      "(1,3)": 19.3769
      "(2,3)": 20.6298
otv:
  lines_width: 80
preprocessing:
  ppm: 100  # do not change
  rotate_image: -90
  pre_roi:
  - - 78
    - 1217
  - - 2143
    - 3294
  roi:
  - - 83
    - 109
  - - 1930
    - 2024
  image_correction:
    apply: true
    c: 2
    f: 8.0
    k1: -9.999999747378752e-06
    camera_matrix:
      - - 2343.874030606418
        - 0
        - 1750.257150554386
      - - 0
        - 2337.355572222067
        - 987.3723075141146
      - - 0
        - 0
        - 1
    dist_coeffs:
      - - -0.45835142200388956
        - 0.45271600570178333
        - 0.0023286643488378066
        - -0.0018160985370820142
        - -0.2349399150200533
water_flow:
  area: 0
  profile:
    height: 0.17
    depths:
      - x: 1161
        y: 18
        z: 0.3
      - x: 1161
        y: 129
        z: 0.5
      - x: 1161
        y: 241
        z: 0.6
      - x: 1160
        y: 352
        z: 0.7
      - x: 1160
        y: 463
        z: 0.9
      - x: 1160
        y: 574
        z: 1.2
      - x: 1159
        y: 686
        z: 1.5
      - x: 1159
        y: 797
        z: 1.3
      - x: 1159
        y: 908
        z: 1.2
      - x: 1159
        y: 1019
        z: 1.2
      - x: 1158
        y: 1131
        z: 1.2
      - x: 1158
        y: 1242
        z: 1.2
      - x: 1158
        y: 1353
        z: 1.1
      - x: 1157
        y: 1464
        z: 0.9
      - x: 1157
        y: 1575
        z: 0.8
      - x: 1157
        y: 1687
        z: 0.8
      - x: 1156
        y: 1798
        z: 0.6
