site_name: AWIVE
site_url: https://josephpenaquino.github.io/awive
theme: material

nav:
  - Home: index.md
  - Features:
    - Plots: features/plots

plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          parameter_headings: false
          show_root_full_path: true
          show_root_heading: true
          show_root_members_full_path: true
          group_by_category: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          show_category_heading: true


