name: Python Ruff Check
on: [push, pull_request]

jobs:
  python-ruff-check:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        id: setup_python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Restore cached virtualenv
        uses: actions/cache/restore@v4
        with:
          key: venv-${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('uv.lock') }}
          path: .venv

      - name: Install the project
        run: |
          uv sync --all-extras --all-groups
          uv pip install ruff

      - name: Saved cached virtualenv
        uses: actions/cache/save@v4
        with:
          key: venv-${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('uv.lock') }}
          path: .venv

      - name: Run Ruff
        run: uv run ruff check --output-format=github .
